version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mail-app
    restart: always
    working_dir: /var/www/
    volumes:
      - ../:/var/www
  nginx:
    image: nginx:1.19-alpine
    container_name: mail-nginx
    restart: always
    ports:
      - 8000:80
    volumes:
      - ../:/var/www
      - ./nginx:/etc/nginx/conf.d
  mailhog:
    container_name: mail-mailhog
    image: mailhog/mailhog
    restart: always
    logging:
      driver: none
    ports:
      - 8025:8025
      - 1025:1025